# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8772ccddc874119a1e1520cd6c6fa13be891311b82c9c11bdef9a4355083fc084943118e84637f91758fb3a676b7f8acb1223b90c679a7215e1d4241ca910592

test:
  secret_key_base: a8f2bed471b7405d070631876f687dbd3d3e71b6ee498db3e4383e955b99bef86cfdc19100be0aa84fd289308dbabe89d33d1554457f1a1f2d178e502932d84e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
